// System-wide constants for RazorGuard AI Risk Engine

const RISK_VECTOR = {
  CARDING_ATTACK: 'CARDING_ATTACK',
  HIGH_AMOUNT_GEO_MISMATCH: 'HIGH_AMOUNT_GEO_MISMATCH',
  RTO_COD_ABUSE: 'RTO_COD_ABUSE',
  ACCOUNT_TAKEOVER: 'ACCOUNT_TAKEOVER',
  MERCHANT_VELOCITY_SPIKE: 'MERCHANT_VELOCITY_SPIKE',
  CHARGEBACK_DISPUTE_ABUSE: 'CHARGEBACK_DISPUTE_ABUSE',
  SUSPICIOUS_BIN_ATTACK: 'SUSPICIOUS_BIN_ATTACK',
  LEGITIMATE_TRANSACTION: 'LEGITIMATE_TRANSACTION'
};

const RISK_ACTION = {
  APPROVE: 'APPROVE',
  STEP_UP_AUTH: 'STEP_UP_AUTH',
  HOLD_PAYOUT: 'HOLD_PAYOUT',
  BLOCK_AND_FREEZE: 'BLOCK_AND_FREEZE'
};

const DEFAULT_THRESHOLDS = {
  APPROVE_MAX_SCORE: 30,
  STEP_UP_MAX_SCORE: 65,
  HOLD_PAYOUT_MAX_SCORE: 85,
  VELOCITY_MAX_PER_MINUTE: 4,
  AMOUNT_MULTIPLIER_WARNING: 3.0,
  HIGH_RISK_RTO_SCORE: 0.70
};

const RISK_LABELS = {
  [RISK_VECTOR.CARDING_ATTACK]: 'High-Velocity Carding Attack',
  [RISK_VECTOR.HIGH_AMOUNT_GEO_MISMATCH]: 'High Amount & IP Geo Anomaly',
  [RISK_VECTOR.RTO_COD_ABUSE]: 'RTO / Return Fraud Abuse',
  [RISK_VECTOR.ACCOUNT_TAKEOVER]: 'Account Takeover / Device Shift',
  [RISK_VECTOR.MERCHANT_VELOCITY_SPIKE]: 'Sudden Merchant Velocity Spike',
  [RISK_VECTOR.CHARGEBACK_DISPUTE_ABUSE]: 'Friendly Fraud / Dispute Abuse',
  [RISK_VECTOR.SUSPICIOUS_BIN_ATTACK]: 'Suspicious Prepaid / Virtual Card Attack',
  [RISK_VECTOR.LEGITIMATE_TRANSACTION]: 'Legitimate Low-Risk Transaction'
};

module.exports = {
  RISK_VECTOR,
  RISK_ACTION,
  DEFAULT_THRESHOLDS,
  RISK_LABELS
};
